<?php

namespace App\Console\Commands;

use App\Services\CountryEnv;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Process;
use RuntimeException;

use function Laravel\Prompts\select;

/**
 * Points a local dev session at one country's site by composing `.env` from the
 * local layers plus that country's deployment overlay. See {@see CountryEnv} for
 * the layering; this command is the shell around it, plus the work that a switch
 * needs beyond the env file itself.
 */
#[Signature('env:use
    {country? : Overlay directory to switch to (e.g. usa, au); prompts when omitted}
    {--show : Print the country the current .env was generated for and exit}
    {--dry-run : Report what would change without writing .env}
    {--no-post : Skip the cache flush and the cmsRoutes.ts regeneration}')]
#[Description('Switch local dev to another country by composing .env from its overlay')]
class UseCountryEnv extends Command
{
    public function handle(CountryEnv $env): int
    {
        $countries = $env->countries();
        $current = $env->currentCountry();

        if ($this->option('show')) {
            $this->components->info($current === null
                ? '.env was not generated by env:use (no country marker).'
                : "Local .env is composed for: {$current}");

            return self::SUCCESS;
        }

        if ($countries === []) {
            $this->components->error('No countries found — deploy/k8s/overlays/*/config.env matched nothing.');

            return self::FAILURE;
        }

        $country = $this->resolveCountry($countries, $current);

        if (! in_array($country, $countries, true)) {
            $this->components->error("Unknown country [{$country}]. Available: ".implode(', ', $countries));

            return self::FAILURE;
        }

        try {
            foreach ([$env->sharedPath(), $env->countryPath($country)] as $layer) {
                if ($env->ensureLayer($layer) !== null) {
                    $this->components->info('Created '.basename($layer).' from its .example — fill in the blanks.');
                }
            }
        } catch (RuntimeException $exception) {
            $this->components->error($exception->getMessage());

            return self::FAILURE;
        }

        $plan = $env->compose($country);

        if (! $this->assertComplete($plan, $env, $country)) {
            return self::FAILURE;
        }

        foreach ($plan['absent'] as $key) {
            $this->components->warn("{$key} is not set for {$country} — whatever reads it degrades locally.");
        }

        if ($plan['carriedAppKey']) {
            $this->components->warn('APP_KEY carried over from the outgoing .env. Paste it into .env.local.shared so it stops depending on the previous file.');
        }

        $diff = $env->diff($plan['values']);

        if ($this->option('dry-run')) {
            return $this->reportDryRun($country, $diff);
        }

        $backup = $env->write($plan['body']);

        $this->components->info("Local .env now composed for {$country}.");

        if ($backup !== null) {
            $this->components->twoColumnDetail('previous .env saved to', basename($backup));
        }

        $this->components->twoColumnDetail('keys added / changed / removed', sprintf(
            '%d / %d / %d',
            count($diff['added']),
            count($diff['changed']),
            count($diff['removed']),
        ));

        if (! $this->option('no-post')) {
            $this->runPostSteps();
        }

        $this->newLine();
        $this->components->warn('Still yours to do: restart `composer dev` (Vite has the old build-time env inlined and Octane workers hold the old config), and run `php artisan migrate` if this country\'s local database is new.');

        return self::SUCCESS;
    }

    /**
     * @param  list<string>  $countries
     */
    private function resolveCountry(array $countries, ?string $current): string
    {
        $argument = $this->argument('country');

        if (is_string($argument)) {
            return $argument;
        }

        return select(
            label: 'Which country should local dev point at?',
            options: array_combine($countries, $countries),
            default: $current !== null && in_array($current, $countries, true) ? $current : null,
        );
    }

    /**
     * A half-composed env is worse than a failed switch: a missing COUNTRY falls
     * back to `US` and a missing GD_WEBSITE_ID to null, so the site comes up
     * looking fine while serving another country's content. Refuse instead.
     *
     * @param  array{missingIdentity: list<string>, missingLocal: list<string>, ...}  $plan
     */
    private function assertComplete(array $plan, CountryEnv $env, string $country): bool
    {
        if ($plan['missingIdentity'] !== []) {
            $this->components->error("deploy/k8s/overlays/{$country}/config.env is missing keys this site cannot run without:");
            $this->components->bulletList($plan['missingIdentity']);
            $this->line('  Add them to that overlay (they are the deployed values too), or override them in '.basename($env->countryPath($country)).'.');
        }

        if ($plan['missingLocal'] !== []) {
            $this->components->error(basename($env->countryPath($country)).' is missing keys that have no safe default on a developer machine:');
            $this->components->bulletList($plan['missingLocal']);
        }

        return $plan['missingIdentity'] === [] && $plan['missingLocal'] === [];
    }

    /**
     * @param  array{added: list<string>, changed: list<string>, removed: list<string>}  $diff
     */
    private function reportDryRun(string $country, array $diff): int
    {
        $this->components->info("Dry run — .env untouched. Switching to {$country} would:");

        foreach (['added' => 'add', 'changed' => 'change', 'removed' => 'remove'] as $bucket => $verb) {
            if ($diff[$bucket] !== []) {
                $this->line("  {$verb}:");
                $this->components->bulletList($diff[$bucket]);
            }
        }

        if ($diff['added'] === [] && $diff['changed'] === [] && $diff['removed'] === []) {
            $this->components->info('Nothing would change.');
        }

        return self::SUCCESS;
    }

    /**
     * The work a country switch needs beyond the env file. Each runs as a fresh
     * process on purpose: this one booted against the OUTGOING .env, so an
     * in-process call would clear the wrong country's caches.
     *
     * All three are non-fatal — .env is already written by the time they run, and
     * a country whose database or CMS is not reachable yet should still switch.
     */
    private function runPostSteps(): void
    {
        $steps = [
            'optimize:clear' => 'config, route and view caches',
            // The SDK's cache key is sha1(baseUri|clientId) and does NOT include
            // GD_WEBSITE_ID, so two countries sharing an OAuth client would serve
            // each other's cached content.
            'cache:clear' => 'application cache, including the GorillaDash SWR entries',
            // Route names and paths for the CMS-driven pages come from this
            // country's website, so the generated types are country-specific.
            'cms-routes:types' => 'resources/ts/types/cmsRoutes.ts',
        ];

        $this->newLine();

        foreach ($steps as $artisan => $what) {
            $result = null;

            $this->components->task("{$artisan} — {$what}", function () use (&$result, $artisan): bool {
                $result = Process::path(base_path())->run([PHP_BINARY, 'artisan', $artisan]);

                return $result->successful();
            });

            if ($result !== null && ! $result->successful()) {
                $reason = strtok(trim($result->errorOutput() ?: $result->output()), "\n");

                $this->components->warn("{$artisan} skipped: ".($reason === false ? 'no output' : $reason));
            }
        }
    }
}
