<?php

namespace App\Services;

use App\Enums\Locale;
use Illuminate\Routing\Route;
use Illuminate\Routing\Router;
use ReflectionException;
use ReflectionMethod;

/**
 * The CMS-driven routes' URI templates, shared with the frontend as the `cmsRoutes`
 * Inertia prop: route name => ['uri' => '/{page}/{slug}', 'page' => 'locations'].
 *
 * This is what lets the frontend build a sub-route URL from a route NAME —
 * `cmsRoute('locations.show', { slug })` in resources/ts/lib/pagePaths.ts — without
 * Wayfinder (whose URIs are baked into the bundle at build time) and without a
 * hand-written helper per route. Templates come from the live route table, so a new
 * sub-route in routes/web.php reaches the frontend with no frontend change; only the
 * `{page}` placeholder is CMS data, filled at call time from the `pages` prop.
 *
 * A route is CMS-driven exactly when it carries a keyed `page:` middleware
 * (EnsureWebsitePage) — the key names the logical page whose current slug fills
 * `{page}`. The keyless single-segment route is excluded: its `{page}` IS the lookup
 * key, which pagePath() already covers. So are the `locale.`-prefixed duplicates —
 * templates are locale-free like every path the frontend builds; localizedUrl()
 * attaches the prefix at runtime.
 */
class CmsRoutes
{
    public function __construct(
        private readonly Router $router,
        private readonly WebsitePages $pages,
    ) {
    }

    /**
     * Route name => URI template + the logical page key that fills `{page}`.
     *
     * @return array<string, array{uri: string, page: string}>
     */
    public function templates(): array
    {
        $templates = [];

        foreach ($this->routes() as $name => $route) {
            $templates[$name] = ['uri' => '/'.$route->uri(), 'page' => (string) $this->pageKey($route)];
        }

        return $templates;
    }

    /**
     * Route name => route object, for every CMS-driven route.
     *
     * @return array<string, Route>
     */
    private function routes(): array
    {
        $routes = [];

        foreach ($this->router->getRoutes() as $route) {
            $name = $route->getName();

            if ($name === null || $this->pageKey($route) === null || str_starts_with($name, 'locale.')) {
                continue;
            }

            $routes[$name] = $route;
        }

        return $routes;
    }

    /**
     * The generated resources/ts/types/cmsRoutes.ts: the CmsRouteParams compile-time
     * types for cmsRoute() (route name => URL parameter names), plus the two runtime
     * FALLBACK constants the frontend serves until the shared props land. Baking
     * these is safe where baking Wayfinder's URIs was not — the types change exactly
     * when the route definitions do (a deploy), and the fallbacks render from PHP
     * CONSTANTS (WebsitePages::FALLBACK, the route table), never a CMS read, so the
     * `{page}` segment's live VALUE stays runtime data. The output is gitignored and
     * regenerated on every vite dev/build (vite.config.ts), exactly like the
     * Wayfinder output; `cms-routes:types` is the standalone command. One part IS
     * environment-dependent: each member's @route line resolves `{page}` through
     * THIS environment's CMS map (WebsitePages, default locale) at generation time
     * — a dev-time snapshot, never runtime data.
     */
    public function typeDeclarations(): string
    {
        $paths = $this->pages->paths(Locale::default());

        $members = collect($this->routes())
            ->map(fn (Route $route, string $name): string => $this->typeMember($name, $route, $paths))
            ->implode("\n");

        $fallbackPaths = collect(WebsitePages::FALLBACK)
            ->map(fn (string $slug, string $key): string => $key === 'homepage' ? '/' : '/'.$slug)
            // Keys are quoted: a logical key is `vue_route_name ?? slug`, so it carries
            // whatever the CMS slug does (`nutrition-facts`, `grazing-tables`), which is
            // not necessarily a valid bare JS identifier — emitted bare, that is a syntax
            // error in the generated module and nothing catches it until the next
            // type-check. `keyof typeof` is unaffected by the quotes.
            ->map(fn (string $path, string $key): string => "  '{$key}': '{$path}'")
            ->implode(",\n");

        $fallbackRoutes = collect($this->routes())
            ->map(fn (Route $route, string $name): string => sprintf(
                "  '%s': { uri: '/%s', page: '%s' }",
                $name,
                $route->uri(),
                $this->pageKey($route),
            ))
            ->implode(",\n");

        return <<<TS
        /**
         * Generated by `php artisan cms-routes:types` — do not edit (gitignored; vite
         * regenerates it on every dev/build, like the Wayfinder output).
         *
         * The CMS-driven routes' compile-time face: CmsRouteParams types cmsRoute()'s
         * names and params, and the FALLBACK constants are what the frontend serves
         * until the `pages` / `cmsRoutes` shared props land. All of it renders from
         * routes/web.php and PHP constants — the `{page}` segment's live value stays
         * runtime CMS data; only the @route docblocks show it resolved through this
         * environment's CMS map as of generation time.
         */
        export interface CmsRouteParams {
        {$members}
        }

        /** Logical page key → locale-free path (App\Services\WebsitePages::FALLBACK). */
        export const PAGE_PATH_FALLBACK = {
        {$fallbackPaths}
        } as const

        /** Logical page keys the CMS map may be asked for. */
        export type PageKey = keyof typeof PAGE_PATH_FALLBACK

        /** route name → URI template + the page whose slug fills `{page}` (routes/web.php). */
        export const CMS_ROUTE_FALLBACK: Record<string, { uri: string; page: string }> = {
        {$fallbackRoutes}
        }

        TS;
    }

    /**
     * One CmsRouteParams member: a Wayfinder-style docblock (@see the controller
     * action and its file:line, @route the URI) over the `'name': { params }` line.
     * The @route line shows the URI with `{page}` already resolved through the CMS
     * map passed in — the current environment's value at generation time. Both the
     * line numbers and the resolved path may drift as controllers and the CMS move;
     * the next vite dev/build regenerates them, exactly like Wayfinder's output.
     *
     * @param  array<string, string>  $paths  logical page key => current path
     */
    private function typeMember(string $name, Route $route, array $paths): string
    {
        preg_match_all('/\{(\w+)\}/', $route->uri(), $matches);

        $params = array_values(array_diff($matches[1], ['page']));

        $shape = $params === []
            ? 'Record<string, never>'
            : '{ '.implode('; ', array_map(fn (string $param): string => "{$param}: string", $params)).' }';

        $key = (string) $this->pageKey($route);
        $slug = ltrim($paths[$key] ?? '/'.$key, '/');
        $currentUri = '/'.str_replace('{page}', $slug, $route->uri());

        $lines = ['  /**'];

        foreach ($this->actionSees($route) as $see) {
            $lines[] = "   * @see {$see}";
        }

        $lines[] = "   * @route '{$currentUri}'";
        $lines[] = '   */';
        $lines[] = "  '{$name}': {$shape}";

        return implode("\n", $lines);
    }

    /**
     * `@see` targets for the route's controller action, Wayfinder-style: the
     * FQCN::method and its file:line (relative to the repo root). Empty for
     * closure routes or an unreflectable action.
     *
     * @return list<string>
     */
    private function actionSees(Route $route): array
    {
        $action = $route->getActionName();

        if ($action === 'Closure') {
            return [];
        }

        [$class, $method] = str_contains($action, '@')
            ? explode('@', $action, 2)
            : [$action, '__invoke'];

        try {
            $reflection = new ReflectionMethod($class, $method);
        } catch (ReflectionException) {
            return [];
        }

        $sees = ['\\'.$class.'::'.$method];

        $file = $reflection->getFileName();

        if (is_string($file)) {
            $sees[] = ltrim(str_replace(base_path(), '', $file), '/').':'.$reflection->getStartLine();
        }

        return $sees;
    }

    /**
     * The logical page key from a keyed `page:` middleware, or null when the route
     * carries none (i.e. is not a CMS sub-route).
     */
    private function pageKey(Route $route): ?string
    {
        foreach ($route->middleware() as $middleware) {
            if (is_string($middleware) && str_starts_with($middleware, 'page:')) {
                return substr($middleware, strlen('page:'));
            }
        }

        return null;
    }
}
