/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
import type * as Types from '../graphql/__generated__/types';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type MediaCollectionInfoFragment = { name: string | null, description: string | null, media: Array<{ default: string, thumbnail: string, banner: string, square: string, rectangle: string, original_cropped: string, portrait: string, alt_tag: string | null, approved: boolean | null }> };

export type MediaInfoFragment = { default: string, thumbnail: string, banner: string, square: string, rectangle: string, original_cropped: string, portrait: string, alt_tag: string | null, approved: boolean | null };

export const MediaInfoFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"MediaInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Media"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"default"}},{"kind":"Field","name":{"kind":"Name","value":"thumbnail"}},{"kind":"Field","name":{"kind":"Name","value":"banner"}},{"kind":"Field","name":{"kind":"Name","value":"square"}},{"kind":"Field","name":{"kind":"Name","value":"rectangle"}},{"kind":"Field","name":{"kind":"Name","value":"original_cropped"}},{"kind":"Field","name":{"kind":"Name","value":"portrait"}},{"kind":"Field","name":{"kind":"Name","value":"alt_tag"}},{"kind":"Field","name":{"kind":"Name","value":"approved"}}]}}]} as unknown as DocumentNode<MediaInfoFragment, unknown>;
export const MediaCollectionInfoFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"MediaCollectionInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"MediaCollection"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"description"}},{"kind":"Field","name":{"kind":"Name","value":"media"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"MediaInfo"}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"MediaInfo"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Media"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"default"}},{"kind":"Field","name":{"kind":"Name","value":"thumbnail"}},{"kind":"Field","name":{"kind":"Name","value":"banner"}},{"kind":"Field","name":{"kind":"Name","value":"square"}},{"kind":"Field","name":{"kind":"Name","value":"rectangle"}},{"kind":"Field","name":{"kind":"Name","value":"original_cropped"}},{"kind":"Field","name":{"kind":"Name","value":"portrait"}},{"kind":"Field","name":{"kind":"Name","value":"alt_tag"}},{"kind":"Field","name":{"kind":"Name","value":"approved"}}]}}]} as unknown as DocumentNode<MediaCollectionInfoFragment, unknown>;